# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2


jobs:
  build:
    docker:
      - image: python:3.6

    steps:
      - checkout

      - run:
          name: install python 3 developer extensions (required for installing stuff on python 3.5)
          command: |
            apt-get install python3-dev

      - run:
          name: install tox
          command: |
            pip install tox

      - run:
          name: tox -r to install and run tests and flake
          command: |
            tox -r
